### ISSUE TITLE
Unable to login after upgrade

### ISSUE THREAD

**Issue by lalyos** [iximiuz/labctl#18]
Since I was upgrading my cli from 0.0.5 to 0.1.6, i'm unalbe to login:

```
$ labctl auth login
labctl: Already logged in. Use 'labctl auth logout' first if you want to log in as a different user.

$ labctl auth logout
labctl: Request failed with status 401: {"error":"Authentication required."}.

$ labctl auth whoami
labctl: Request failed with status 401: {"error":"Authentication required."}.
```

## Workaround

By deleting the file containing the token, fixes this issue:
```
rm -rf ~/.iximiuz/labctl/config.yaml
```

## Reproduce

by playion around with the config file I found a way to reproduce this issue:
just replace the session_id to an invalid value:
```
session_id: fake
```

**Comment by iximiuz** [comment]
Thanks for the report, @lalyos! I see how the auth flow can be improved. At first sight, it sounds like a simple session check from time to time would suffice.

**Comment by iximiuz** [comment]
Let's hope https://github.com/iximiuz/labctl/releases/tag/v0.1.7 fixes it 🤞

**Comment by lalyos** [comment]
yes it does fix the issue! +1
